spring.application.name=sgv-api
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5433/sgv_api}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
